tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  php_code_sniffer: true
  php_changetracking: true
  php_mess_detector: true
  sensiolabs_security_checker: true
  php_cs_fixer:
    config: { level: psr2 }
before_commands:
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require hirak/prestissimo
  - composer install --prefer-dist -o
build:
  environment:
    php:
      version: '7.1'
      ini:
        apc.enabled: 1
        apc.enable_cli: 1
  nodes:
    my-tests:
      tests:
        override:
          -
            command: vendor/bin/behat -f progress
          -
            command: vendor/bin/phpunit --coverage-clover=coverage0
            coverage:
              file: 'coverage0'
              format: 'php-clover'
          - command: php-scrutinizer-run
filter:
    excluded_paths: [build/*, tests/*, docroot/*, features/*, src/Core/Helper/Annotate/*, src/Core/Helper/State/*, src/Core/Helper/Subscriber/*]
