name: Add Issues to project
on:
  issues:
    types:
      - opened
jobs:
  add_issue:
    uses: commercetools/clients-automation/.github/workflows/workflow_issues_pr_to_project.yml@3a829d9ef84bfa93b37a1b08110cae245aeacfc9
    with:
      node_id: ${{ github.event.issue.node_id }}
      org: commercetools
      project: 32
    secrets:
      token: ${{ secrets.PROJECT_TOKEN }}
  label_issues:
    uses: commercetools/clients-automation/.github/workflows/label_non_org_items.yml@3da9e080b5eee64941b576342df8af3ca8b25907
    with:
      org: commercetools
      repository: commercetools-php-sdk
      node_id: ${{ github.event.issue.node_id }}
      login: ${{ github.event.issue.user.login }}
    secrets:
      token: ${{ secrets.PROJECT_TOKEN }}
