name: Add Issues to project
on:
  issues:
    types:
      - opened
jobs:
  add_issues:
    uses: commercetools/clients-automation/.github/workflows/workflow_issues_pr_to_project.yml@v1
    with:
      node_id: ${{ github.event.issue.node_id }}
      org: commercetools
      project: 32
      repository: ${{ github.event.repository.name }}
      login: ${{ github.event.issue.user.login }}
    secrets:
      token: ${{ secrets.PROJECT_TOKEN }}
