name: Add Issues to project
on:
  issues:
    types:
      - opened
jobs:
  add_issue:
    uses: commercetools/clients-automation/.github/workflows/workflow_issues_pr_to_project.yml@305d1520c0bd905939f21f22e20431013c199020
    with:
      node_id: ${{ github.event.issue.node_id }}
      org: ${{ github.event.issue.repository.owner.login }}
      project: 32
      repository: ${{ github.event.issue.repository.name }}
      login: ${{ github.event.issue.user.login }}
    secrets:
      token: ${{ secrets.PROJECT_TOKEN }}
