name: Add Issues to project
on:
  issues:
    types:
      - opened
jobs:
  add_issue:
    uses: commercetools/clients-automation/.github/workflows/workflow_issues_pr_to_project.yml@499e0e1b76a64fb0387386067b3492568f06d71d
    with:
      node_id: ${{ github.event.issue.node_id }}
      org: commercetools
      project: 32
      repository: commercetools-php-sdk
      login: ${{ github.event.issue.user.login }}
    secrets:
      token: ${{ secrets.PROJECT_TOKEN }}
